rrt:
  ros__parameters:
    waypoints_path: "/home/f1tenth/lab_ws25/src/rrt/racelines/FTM_clean_ws25.csv" 
    odom_topic:  "/pf/pose/odom"
  # segments = Number of points to interpolate to. The bigger the map, the more the number of segments
  # TODO: Make this automatically infer?
    segments: 40 
    K_p: 1.0
    velocity_min: 1.0
    velocity_max: 1.5
    steering_limit: 15.0
    cells_per_meter: 10
    lookahead_distance: 1.5

    # Idea taken from Pure Pursuit
    # Lookahead is computed using the following: lookahead = min(max(min_lookahead, max_lookahead * curr_velocity / lookahead_ratio), max_lookahead); 
    min_lookahead: 0.5
    max_lookahead: 1.5 # lookahead when the car is going around max velocity
    lookahead_ratio: 8.0 # approximately the max velocity
    is_sim: False
